#encoding='utf-8'

[web]
secret_key = your_secret_key_here
#plz must edit it orz

[litebans]
database_host = localhost
#if no port default 3306
database_user = root
database_password = 
database_name = litebans

[auth]
database_host = localhost
#if no port default 3306
database_user = root
database_password = 
database_name = 


[game]
ip=127.0.0.1
port=3024

[log]
enable=false

[unban]
mode = whitelist
#choose blacklist to enter reject reason
#choose whitelist to enter pass reason
reason =["reason 1",
         "reason 2",
         "etc"]
